name: Update profile Views

on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  update-profile-views:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Update Profile Views
        run: |
          ls
