name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Remove files
        run: |
          rm ./*svg
      
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          filename: sample.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: cycool29
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kuala_Lumpur
      
      - name: Remove footer message
        run: |
          ls -A
          cat ./sample.svg | grep -v "footer>\|These metrics include private contributions\|Last updated" > ./github-metrics.svg
          rm ./sample.svg
