name: Update Profile Views

on:
  schedule:
    - cron: '*/5  * * * *'
  workflow_dispatch:
  push: {branches: ["main"]}

env:
  COLOR: 00ff00

jobs:
  update-profile-views:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update Profile Views
        run: |
          VIEWS="$(${{ secrets.PROFILE_VIEWS }} 2>/dev/null | jq | grep -B 2 '"hash": "3egL4dg"' | head -n 1 | grep -o "[1234567890]*")"          
          echo '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="220" height="20" role="img" aria-label="cycool29&apos;s GitHub Profile Views: 1000"><title>cycool29&apos;s GitHub Profile Views: 1000</title><linearGradient id="s" x2="0" y2="100%"><stop offset="0" stop-color="#bbb" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><clipPath id="r"><rect width="220" height="20" rx="3" fill="#fff"/></clipPath><g clip-path="url(#r)"><rect width="183" height="20" fill="#555"/><rect x="183" width="37" height="20" fill="#4c1"/><rect width="220" height="20" fill="url(#s)"/></g><g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="110"><text aria-hidden="true" x="925" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="1730">cycool29&apos;s GitHub Profile Views</text><text x="925" y="140" transform="scale(.1)" fill="#fff" textLength="1730">cycool29&apos;s GitHub Profile Views</text><text aria-hidden="true" x="2005" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="270">1000</text><text x="2005" y="140" transform="scale(.1)" fill="#fff" textLength="270">1000</text></g></svg>' | sed "s/1000/$VIEWS/g" > profile-views.svg
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git pull
          git add -A
          git diff-index --quiet HEAD || git commit -m "Update profile views to ${VIEWS}"
          git push          
