name: Update profile Views

on:
  schedule:
    - cron: '*/5  * * * *'
  workflow_dispatch:

jobs:
  update-profile-views:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Update Profile Views
        run: |
          sed -i "s+views.*-success+views-$(curl -s -H "Authorization: Bearer 4fe1868e08a58e996b1ede70ddad057b39eb5b9c" -X GET "https://api-ssl.bitly.com/v4/bitlinks/bit.ly/cycool29-profile/clicks/summary" 2>&1 | sed "s/.*total_clicks//" | sed s/units.*//g  | egrep -o [0-9.])-success+g" ./READ*          
          cat ./README.md
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add .
          git commit -m "Update profile views to $(curl -s -H 'Authorization: Bearer ${{ secrets.BITLY_TOKEN }}' -X GET "https://api-ssl.bitly.com/v4/bitlinks/bit.ly/cycool29-profile/clicks/summary" 2>&1 | sed 's/.*total_clicks//' | sed s/units.*//g  | egrep -o '[0-9.]+')"
          git push          
